-- v14: Security department (visitor/delivery/inhouse gate log, gates, keys,
-- guard post shifts, incidents, panic button) merged in as a third
-- department alongside rebar/cement. Additive only — nothing existing is
-- touched beyond widening two CHECK constraints to allow 'security'.
--
-- Applied live to jiltqrunlpewqkofzulz via MCP. This file is the local
-- record of that state, matching the v2..v13 convention.

alter table public.user_department_access
  drop constraint user_department_access_department_check,
  add constraint user_department_access_department_check
    check (department in ('rebar','cement','security'));

alter table public.department_nav_permissions
  drop constraint department_nav_permissions_department_check,
  add constraint department_nav_permissions_department_check
    check (department in ('rebar','cement','security'));

-- ── ENTRIES (visitor / delivery / inhouse) ──────────────────────────────
create table public.security_entries (
  id integer generated by default as identity primary key,
  category text not null check (category in ('visitor','delivery','inhouse','security_event')),
  person_name text not null,
  company text,
  purpose text,
  vehicle_no text,
  badge_no text,
  reference_no text,
  notes text,
  photo_drive_id text,          -- Google Drive file id; see src/lib/google-drive.ts
  status text not null default 'in' check (status in ('in','out')),
  time_in timestamptz not null,
  time_out timestamptz,
  created_at timestamptz not null default now(),
  created_by text,
  abnormal_flag boolean not null default false,
  abnormal_reason text,
  abnormal_type text,
  abnormal_at timestamptz
);

-- ── SITE LAYOUT IMAGE HISTORY ────────────────────────────────────────────
create table public.security_layout (
  id integer generated by default as identity primary key,
  photo_drive_id text not null,
  uploaded_at timestamptz not null default now(),
  uploaded_by text
);

-- ── GATES ────────────────────────────────────────────────────────────────
create table public.security_gates (
  id integer generated by default as identity primary key,
  name text not null,
  pos_x numeric not null default 50,
  pos_y numeric not null default 50,
  status text not null default 'locked' check (status in ('locked','open')),
  updated_at timestamptz not null default now()
);

create table public.security_gate_events (
  id integer generated by default as identity primary key,
  gate_id integer not null references public.security_gates(id),
  gate_name text not null,
  action text not null,
  username text,
  created_at timestamptz not null default now()
);

-- ── KEYS ─────────────────────────────────────────────────────────────────
create table public.security_keys (
  id integer generated by default as identity primary key,
  key_name text not null,
  key_no text,
  description text,
  created_at timestamptz not null default now()
);

create table public.security_key_logs (
  id integer generated by default as identity primary key,
  key_id integer not null references public.security_keys(id),
  key_name text not null,
  issued_to text not null,
  issued_by text not null,
  purpose text,
  time_issued timestamptz not null,
  time_returned timestamptz,
  status text not null default 'out' check (status in ('out','returned')),
  notes text,
  returned_by text
);

-- ── GUARD POSTS + SHIFT LOGS ───────────────────────────────────────────
create table public.security_guard_posts (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.security_post_logs (
  id integer generated by default as identity primary key,
  post_name text not null,
  guard_name text not null,
  time_in timestamptz not null,
  time_out timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  created_by text
);

-- ── INCIDENTS ─────────────────────────────────────────────────────────────
create table public.security_incidents (
  id integer generated by default as identity primary key,
  type text not null,
  description text not null,
  location text,
  reported_by text not null,
  photo_drive_id text,
  severity text not null default 'medium' check (severity in ('low','medium','high')),
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now()
);

-- ── PANIC LOGS ────────────────────────────────────────────────────────────
create table public.security_panic_logs (
  id integer generated by default as identity primary key,
  triggered_by text not null,
  remark text,
  created_at timestamptz not null default now()
);

-- ── RLS: every table gated on department membership, matching cement's
-- existing pattern (per-role restrictions are enforced by nav-hiding, not
-- RLS — the same accepted posture as today's cement "technician" role). ────
do $$
declare
  t text;
begin
  for t in select unnest(array[
    'security_entries','security_layout','security_gates','security_gate_events',
    'security_keys','security_key_logs','security_guard_posts','security_post_logs',
    'security_incidents','security_panic_logs'
  ])
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format($f$create policy "security dept can select" on public.%I for select using (public.has_dept_access('security'))$f$, t);
    execute format($f$create policy "security dept can insert" on public.%I for insert with check (public.has_dept_access('security'))$f$, t);
    execute format($f$create policy "security dept can update" on public.%I for update using (public.has_dept_access('security'))$f$, t);
    execute format($f$create policy "security dept can delete" on public.%I for delete using (public.has_dept_access('security'))$f$, t);
  end loop;
end $$;

-- Panic banner uses Supabase Realtime instead of the legacy app's custom SSE
-- endpoint (no long-lived connections on serverless).
alter publication supabase_realtime add table public.security_panic_logs;

-- Nav permission defaults matching the new /security/* pages — settings is
-- manager+admin ("Boss") only, everything else open to all three roles.
insert into public.department_nav_permissions (department, role, nav_key) values
  ('security','admin','/security'), ('security','manager','/security'), ('security','security','/security'),
  ('security','admin','/security/entries'), ('security','manager','/security/entries'), ('security','security','/security/entries'),
  ('security','admin','/security/gates'), ('security','manager','/security/gates'), ('security','security','/security/gates'),
  ('security','admin','/security/keys'), ('security','manager','/security/keys'), ('security','security','/security/keys'),
  ('security','admin','/security/post-logs'), ('security','manager','/security/post-logs'), ('security','security','/security/post-logs'),
  ('security','admin','/security/incidents'), ('security','manager','/security/incidents'), ('security','security','/security/incidents'),
  ('security','admin','/security/audit'), ('security','manager','/security/audit'), ('security','security','/security/audit'),
  ('security','admin','/security/settings'), ('security','manager','/security/settings');
