-- Migration V10: Merge cement-app into RebarPro.
--
-- This is applied to jiltqrunlpewqkofzulz ("RebarPro"), the project this app's
-- .env.local actually points to. It already has the live rebar schema
-- (profiles, projects, project_types, rebar_sizes, transactions, stock_takes,
-- global_settings, audit_log, targets) with real production data — those
-- tables are NOT recreated here, only their RLS is tightened. Everything else
-- below (cement_*, user_department_access) is new.
--
-- (Earlier in this session this was mistakenly applied to a different,
-- unrelated Supabase project — wbmsvhuyvfdlnwonukan — and has since been
-- rolled back there in full.)

-- ============================================================
-- 1. CEMENT DEPARTMENT TABLES (ported from cement-app/server.js initDB(),
--    integer PKs preserved so SQLite row IDs migrate over unchanged;
--    cement_users dropped in favor of shared auth + user_department_access)
-- ============================================================

create table public.cement_units (
  id integer generated by default as identity primary key,
  name text unique not null
);

create table public.cement_plants (
  id integer generated by default as identity primary key,
  name text unique not null,
  is_active boolean not null default true
);

create table public.cement_materials (
  id integer generated by default as identity primary key,
  name text unique not null,
  unit_id integer references public.cement_units(id),
  is_active boolean not null default true,
  batching_req numeric default 0
);

create table public.cement_silos (
  id integer generated by default as identity primary key,
  plant_id integer references public.cement_plants(id),
  name text not null,
  capacity numeric,
  current_stock numeric default 0,
  is_active boolean not null default true,
  display_order integer default 0,
  bg_color text default '#ffffff'
);

create table public.cement_silo_materials (
  id integer generated by default as identity primary key,
  silo_id integer unique references public.cement_silos(id),
  material_id integer references public.cement_materials(id)
);

create table public.cement_silo_material_history (
  id integer generated by default as identity primary key,
  silo_id integer not null references public.cement_silos(id),
  material_id integer not null references public.cement_materials(id),
  effective_from date not null default '2000-01-01',
  effective_to date
);

create table public.cement_suppliers (
  id integer generated by default as identity primary key,
  name text unique not null,
  is_active boolean not null default true
);

create table public.cement_weight_in (
  id integer generated by default as identity primary key,
  supplier text,
  weigh_date date,
  do_number text,
  lorry_no text,
  trailer_no text,
  material text,
  discharge_to text,
  seal_no text,
  file1_path text,
  file2_path text,
  do_weight numeric,
  weight_in numeric,
  weight_out numeric,
  difference numeric,
  difference_pct numeric,
  created_at timestamptz not null default now(),
  unload_start_time timestamptz,
  unload_complete_time timestamptz,
  target_weight_out numeric,
  weight_out_operator text,
  weight_out_time timestamptz,
  plant_id integer references public.cement_plants(id),
  silo_id integer references public.cement_silos(id),
  material_id integer references public.cement_materials(id)
);

create table public.cement_daily_stock_take (
  id integer generated by default as identity primary key,
  take_date date not null,
  silo_id integer not null references public.cement_silos(id),
  actual_stock numeric not null,
  operator text,
  unique (take_date, silo_id)
);

create table public.cement_daily_usage (
  id integer generated by default as identity primary key,
  usage_date date not null,
  silo_id integer not null references public.cement_silos(id),
  usage numeric not null,
  operator text,
  unique (usage_date, silo_id)
);

create table public.cement_alert_settings (
  id integer primary key check (id = 1),
  manager_email text,
  variance_threshold_pct numeric
);
insert into public.cement_alert_settings (id, manager_email, variance_threshold_pct) values (1, 'manager@example.com', 3);

create table public.cement_alert_log (
  id integer generated by default as identity primary key,
  alert_date date,
  plant_name text,
  material_name text,
  variance_pct numeric,
  created_at timestamptz not null default now()
);

create table public.cement_transfers (
  id integer generated by default as identity primary key,
  transfer_date date not null,
  from_silo_id integer not null references public.cement_silos(id),
  to_silo_id integer not null references public.cement_silos(id),
  material_id integer not null references public.cement_materials(id),
  quantity numeric not null,
  remarks text,
  operator text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- 2. SHARED ACCESS CONTROL
-- ============================================================

create table public.user_department_access (
  user_id uuid references public.profiles(id) on delete cascade not null,
  department text not null check (department in ('rebar','cement')),
  role text not null,
  granted_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  primary key (user_id, department)
);

create or replace function public.has_dept_access(dept text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.user_department_access uda
    where uda.user_id = auth.uid() and uda.department = dept
  );
$$;

create or replace function public.is_dept_admin(dept text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.user_department_access uda
    where uda.user_id = auth.uid() and uda.department = dept and uda.role = 'admin'
  );
$$;

grant execute on function public.has_dept_access(text) to authenticated;
grant execute on function public.is_dept_admin(text) to authenticated;

alter table public.user_department_access enable row level security;
create policy "self can view own access rows" on public.user_department_access for select using (user_id = auth.uid());
create policy "dept admins can view dept rows" on public.user_department_access for select using (public.is_dept_admin(department));
create policy "dept admins can grant dept rows" on public.user_department_access for insert with check (public.is_dept_admin(department));
create policy "dept admins can update dept rows" on public.user_department_access for update using (public.is_dept_admin(department));
create policy "dept admins can revoke dept rows" on public.user_department_access for delete using (public.is_dept_admin(department));

-- Seed: the account driving this merge becomes admin of both departments;
-- the other two existing rebar users keep rebar access (their current level
-- of access, since every authenticated user already had full rebar read/write).
insert into public.user_department_access (user_id, department, role)
select p.id, 'rebar', case when u.email = 'davidthen4285@gmail.com' then 'admin' else 'user' end
from public.profiles p join auth.users u on u.id = p.id
on conflict do nothing;

insert into public.user_department_access (user_id, department, role)
select p.id, 'cement', 'admin'
from public.profiles p join auth.users u on u.id = p.id
where u.email = 'davidthen4285@gmail.com'
on conflict do nothing;

-- ============================================================
-- 3. TIGHTEN RLS ON EXISTING REBAR TABLES
--    Today any authenticated user (in this whole Supabase project) can read/
--    write every rebar table. Once cement accounts share this project that
--    would let cement-only staff see/edit rebar data. Replace the blanket
--    "authenticated" policies with department-membership checks.
-- ============================================================

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'projects','project_types','rebar_sizes','transactions','stock_takes','targets'
  ] loop
    execute format('drop policy if exists "Authenticated users can read %s" on public.%I', tbl, tbl);
    execute format('drop policy if exists "Authenticated users can insert %s" on public.%I', tbl, tbl);
    execute format('drop policy if exists "Authenticated users can update %s" on public.%I', tbl, tbl);
    execute format('drop policy if exists "Authenticated users can delete %s" on public.%I', tbl, tbl);
    execute format('create policy "rebar members select" on public.%I for select using (public.has_dept_access(''rebar''))', tbl);
    execute format('create policy "rebar members insert" on public.%I for insert with check (public.has_dept_access(''rebar''))', tbl);
    execute format('create policy "rebar members update" on public.%I for update using (public.has_dept_access(''rebar''))', tbl);
    execute format('create policy "rebar members delete" on public.%I for delete using (public.has_dept_access(''rebar''))', tbl);
  end loop;
end $$;

-- global_settings: keep public read (it's just unit/coverage-day preferences),
-- but require rebar membership to change it.
drop policy if exists "Authenticated users can insert global_settings" on public.global_settings;
drop policy if exists "Authenticated users can update global_settings" on public.global_settings;
create policy "rebar members update global_settings" on public.global_settings for update using (public.has_dept_access('rebar'));
create policy "rebar members insert global_settings" on public.global_settings for insert with check (public.has_dept_access('rebar'));

-- audit_log: append-only for rebar members, no update/delete.
drop policy if exists "Authenticated users can read audit_log" on public.audit_log;
drop policy if exists "Authenticated users can insert audit_log" on public.audit_log;
create policy "rebar members select audit_log" on public.audit_log for select using (public.has_dept_access('rebar'));
create policy "rebar members insert audit_log" on public.audit_log for insert with check (public.has_dept_access('rebar'));

-- ============================================================
-- 4. RLS ON NEW CEMENT TABLES
-- ============================================================

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'cement_units','cement_plants','cement_materials','cement_silos','cement_silo_materials',
    'cement_silo_material_history','cement_suppliers','cement_weight_in','cement_daily_stock_take',
    'cement_daily_usage','cement_alert_settings','cement_transfers'
  ] loop
    execute format('alter table public.%I enable row level security', tbl);
    execute format('create policy "cement members select" on public.%I for select using (public.has_dept_access(''cement''))', tbl);
    execute format('create policy "cement members insert" on public.%I for insert with check (public.has_dept_access(''cement''))', tbl);
    execute format('create policy "cement members update" on public.%I for update using (public.has_dept_access(''cement''))', tbl);
    execute format('create policy "cement members delete" on public.%I for delete using (public.has_dept_access(''cement''))', tbl);
  end loop;

  execute 'alter table public.cement_alert_log enable row level security';
  execute 'create policy "cement members select" on public.cement_alert_log for select using (public.has_dept_access(''cement''))';
  execute 'create policy "cement members insert" on public.cement_alert_log for insert with check (public.has_dept_access(''cement''))';
end $$;

NOTIFY pgrst, 'reload schema';
